config/routes.rb
IosAcademyWeb::Application.routes.draw do
  devise_for :admins
  resources :episodes

  devise_for :users
  root :to => 'home#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  has_attached_file :image,
                    styles: { medium: "300x300>", thumb: "100x100>" }

  scope :last_ten, -> { limit(10) }

  def paid_or_free
    return 'Paid' if paid
    return 'Free'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_all!
    authenticate_user! unless admin_signed_in?
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < InheritedResources::Base
  before_filter :authenticate_all!,  except: %i(index show)

  def show
    authenticate_user! if Episode.find(params[:id]).paid && !current_admin
    show!
  end

  private
  def permitted_params
    params.permit!
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @episodes = Episode.last_ten
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.erb
<%= simple_form_for @episode, html: { multipart: true } do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :video_link if @episode.respond_to?(:video_link) %>
    <%= f.input :paid %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<h2>Listing episodes</h2>

<table class='table table-hover'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= image_tag(episode.image.url(:thumb), class: 'img-polaroid') %></td>
        <td><%= episode.title %><br/><span class='label label-info'><%= episode.paid_or_free %></span></td>
        <td><%= episode.description %></td>
        <td><%= link_to 'Show', episode, class: 'btn btn-large' %></td>
        <td><%= link_to('Edit', edit_episode_path(episode), class: 'btn') if current_admin %></td>
        <td><%= link_to('Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger', style: 'color:#FFF') if current_admin %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render 'form' %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<h2><%= @episode.title %></h2>
<h4><span class='label label-info'><%= @episode.paid_or_free %></span></h4>


<div id='video-wrapper'>
  <video id="<%= @episode.video_link %>" class="sublime" width="1024" height="576" data-uid="<%= @episode.video_link %>" data-youtube-id="<%= @episode.video_link %>" preload="none"></video>
</div>

<div style='margin: 10px;'>
  <p class='muted'> <%= @episode.description %> </p>
</div>

<%= link_to 'Edit', edit_episode_path(@episode), class: 'btn' if current_admin %>
<%= link_to 'Back', episodes_path, class: 'btn' %>

app/views/home/index.html.erb
<br/>
<fieldset>
  <legend>Episodes</legend>
  <table class='table table-hover'>
    <thead>
      <th></th>
    </thead>
    <tbody>
      <% @episodes.each do |episode| %>
        <tr>
          <td><h3><%= episode.title %></h3></td>
          <td><%= link_to "Watch", episode, class: 'btn btn-large' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</fieldset>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>iOS Academy Videos</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script type="text/javascript" src="//cdn.sublimevideo.net/js/rocp6kxr.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

  <div role='main' id='content-wrapper'>
    <header>
      <%= link_to raw("<h1>iOS Academy</h1>"), '/' %>
      <%= raw "<div class='alert alert-info'> Currently Signed in as Admin </div>" if current_admin %>
      <%= link_to('Sign In', new_user_session_path,                       class: 'btn btn-primary', style: 'color:#FFFFFF; float:right;') unless current_user %>
      <%= link_to('Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-primary', style: 'color:#FFFFFF; float:right;') if current_user %>
      <%= raw "<p class='notice'> #{notice} </p>" if notice %>
      <%= raw "<p class='alert'>  #{alert} </p>"  if alert  %>
    </header>

    <%= yield %>

    <footer>
    </footer>
  </div>

</body>
</html>